server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /static/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /assets/ {
        expires 7d;
        add_header Cache-Control "public";
    }

    location /ranked-emblems/ {
        expires 7d;
        add_header Cache-Control "public";
    }

    location /api/ {
        proxy_pass http://backend:4000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ~* \.(php|asp|aspx|jsp|cgi|env|git|sql|bak|old|ini|log|sh|py)$ {
        return 403;
    }

    location ~* ^/(wp-|wordpress|phpmyadmin|admin|cgi-bin|\.env|\.git|xmlrpc|vendor|telescope|debug|actuator|console|solr|manager|login\.action) {
        return 403;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
